services:
  nginx:
    image: nginx:latest
    container_name: nginx-jorgegarre
    ports:
      - "80:80"
      - "443:443"

    volumes:
      - ./html:/usr/share/nginx/html/
      - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./conf/htpasswd:/etc/nginx/.htpasswd
      - ./certs/cert.pem:/etc/ssl/certs/cert.pem:ro
      - ./certs/key.pem:/etc/ssl/private/key.pem:ro
    restart: unless-stopped
